<?xml version="1.0"?>
<Security>
    <openFlag>1</openFlag>
    <formCheck>0</formCheck>
	<securityBeanList>

	    <SecurityBean>
	    	<value>cookie</value>
	    	<mvalue>cookie</mvalue>
	    </SecurityBean>
	    <SecurityBean>
	    	<value>Cookie</value>
	    	<mvalue>Cookie</mvalue>
	    </SecurityBean>
	    <SecurityBean>
	    	<value>http</value>
	    	<mvalue>http</mvalue>
	    </SecurityBean>

	    <SecurityBean>
	    	<value>\</value>
	    	<mvalue>%5C</mvalue>
	    </SecurityBean>

	    <SecurityBean>
	    	<value>alert(</value>
	    	<mvalue>alert%28</mvalue>
	    </SecurityBean>
	    <SecurityBean>
	    	<value>alert (</value>
	    	<mvalue>alert%20%28</mvalue>
	    </SecurityBean>
		
		<SecurityBean>
	    	<value>|</value>
	    	<mvalue>%7C</mvalue>
	    </SecurityBean>
		<!--SecurityBean>
	    	<value><![CDATA[&]]></value>
	    	<mvalue>%26</mvalue>
	    </SecurityBean-->
		<!--SecurityBean>
	    	<value>;</value>
	    	<mvalue>%3B</mvalue>
	    </SecurityBean-->
		<SecurityBean>
	    	<value>$</value>
	    	<mvalue>%24</mvalue>
	    </SecurityBean>
		<!--SecurityBean>
	    	<value>%</value>
	    	<mvalue>%25</mvalue>
	    </SecurityBean-->
		<!--SecurityBean>
	    	<value>@</value>
	    	<mvalue>%40</mvalue>
	    </SecurityBean-->
		<SecurityBean>
	    	<value>'</value>
	    	<mvalue>%27</mvalue>
	    </SecurityBean>
	    <SecurityBean>
	    	<value>"</value>
	    	<mvalue>%22</mvalue>
	    </SecurityBean>
		<SecurityBean>
	    	<value>\'</value>
	    	<mvalue>%5C%27</mvalue>
	    </SecurityBean>
		<SecurityBean>
	    	<value>\"</value>
	    	<mvalue>%5C%22</mvalue>
	    </SecurityBean>
		<SecurityBean>
	    	<value><![CDATA[<]]></value>
	    	<mvalue>%3C</mvalue>
	    </SecurityBean>
		<SecurityBean>
	    	<value><![CDATA[>]]></value>
	    	<mvalue>%3E</mvalue>
	    </SecurityBean>
		 <SecurityBean>
	    	<value>(</value>
	    	<mvalue>%28</mvalue>
	    </SecurityBean>
	    <SecurityBean>
	    	<value>)</value>
	    	<mvalue>%29</mvalue>
	    </SecurityBean>
		<SecurityBean>
	    	<value>+</value>
	    	<mvalue>%2B</mvalue>
	    </SecurityBean>
		<SecurityBean>
	    	<value>linefeed</value>
	    	<mvalue>%0A</mvalue>
	    </SecurityBean>
		<SecurityBean>
	    	<value>creturn</value>
	    	<mvalue>%0D</mvalue>
	    </SecurityBean>
	</securityBeanList>
</Security>
